POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "user1",
    "password": "password1"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "newusername": "user1",
    "newpassword": "password1",
    "newname": "uuuu",
    "newemail":"user@m.com"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "newusername": "user2",
    "newpassword": "passwoiruruu",
    "newname": "yergfgfg",
    "newemail":"uryryryy@m.com"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "user2",
    "password": "password1"
}

###

GET http://localhost:3000/

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "ali",
    "password": "password1"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "soo",
    "password": "password"
}


